import { AuthProvider } from '@/context/auth.context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { LoaderProvider } from '@/context/loader.context'
import Header from '@/components/header.component'
import Footer from '@/components/footer.component'
import Loader from './loader'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" style={{ height: '100%' }}>
      <body style={{ height: '100%', display:'flex', flexDirection:'column' }}>
        <LoaderProvider>
          <AuthProvider>
            <Header/>
            <Suspense fallback={<Loader/>}>
              <div style={{flexGrow:'1'}}>
                {children}
              </div>
            </Suspense>
            <Footer/>
          </AuthProvider>
          <Loader />
        </LoaderProvider>

      </body>
    </html>
  )
}
